### ISSUE TITLE
Self-hosting link missing

### ISSUE THREAD

**Issue by janEbert** [smallcloudai/code-contrast#21]
[The target](https://github.com/smallcloudai/code-contrast/tree/main/refact_self_hosting) for the [link about self-hosting in the main README.md](https://github.com/smallcloudai/code-contrast/blame/main/README.md#L7) does not exist.

**Comment by mrpeu** [comment]
> [The target](https://github.com/smallcloudai/code-contrast/tree/main/refact_self_hosting) for the [link about self-hosting in the main README.md](https://github.com/smallcloudai/code-contrast/blame/main/README.md#L7) does not exist.

https://github.com/smallcloudai/refact-self-hosting

**Comment by mitya52** [comment]
@janEbert thanks for your reply! I corrected url
